### ISSUE TITLE
django 1.8 + python 3.4.3 + django-material enabled in template context give following error

### ISSUE THREAD

**Issue by auvipy** [nitely/django-djconfig#13]
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/asif/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/asif/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/asif/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/asif/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/asif/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/home/asif/.pyenv/versions/3.4.3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'djconfigmaterial'

**Comment by auvipy** [comment]
issue resolved after placing the middleware class before django material

**Comment by auvipy** [comment]
python manage.py makemigrations
/home/asif/.pyenv/versions/3.4.3/lib/python3.4/site-packages/djconfig/models.py:10: RemovedInDjango19Warning: Model class djconfig.models.Config doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Config(models.Model):

**Comment by auvipy** [comment]
[27/Jun/2015 17:53:15]"GET / HTTP/1.1" 500 121896
/home/asif/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/contrib/sites/models.py:78: RemovedInDjango19Warning: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Site(models.Model):

/home/asif/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  return f(*args, **kwds)

/home/asif/.pyenv/versions/3.4.3/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  return f(*args, **kwds)

**Comment by nitely** [comment]
I'll get rid of the warnings after Django 1.9 is released.
Pull requests are welcome, though.
